services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      - DOCKER_HOST=unix:///var/run/docker-host.sock
    networks:
      - ghchat-dev

networks:
  ghchat-dev:
    driver: bridge
